name: build

on:
- push
- pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (debian)
        id: docker_build_debian
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./debian.Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ushahidi/debian:bullseye-dockerize

      # - name: Build and push (alpine)
      #   id: docker_build_alpine
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./alpine.Dockerfile
      #     platforms: linux/amd64
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ushahidi/alpine:3.12-dockerize
